services:

  postgres:
    image: postgres:17
    container_name: taskflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: taskflow_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      ##- ./postgres/init:/docker-entrypoint-initdb.d:ro

    networks:
      - taskflow-network
  
  discovery-server:
    image: taskflow/discovery-server:1.0
    container_name: discovery-server

    ports:
      - "8761:8761"

    networks:
      - taskflow-network
      
  api-gateway:
    image: taskflow/api-gateway:1.0
    container_name: api-gateway
    
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile

    ports:
      - "8080:8080"
      - "5005:5005"

    depends_on:
      - discovery-server

    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_TOOL_OPTIONS: >-
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -javaagent:/otel/opentelemetry-javaagent.jar
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      OTEL_SERVICE_NAME: api-gateway
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_TIMEOUT: "30000"
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      #OTEL_LOGS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_INSTRUMENTATION_LOGBACK_APPEND_LOG_EVENTS_TO_SPANS: "true"
      OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"

    networks:
      - taskflow-network

  auth-service:
    image: taskflow/auth-service:1.0
    container_name: auth-service

    depends_on:
      - postgres
      - otel-collector
      - discovery-server
      

    ports:
      - "8081:8081"


    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/taskflow_auth
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: auth-service
      OTEL_EXPORTER_OTLP_TIMEOUT: "30000"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"
      

    networks:
      - taskflow-network
  
  project-service:
    image: taskflow/project-service:1.0
    container_name: project-service

    depends_on:
      - postgres
      - otel-collector
      - kafka
      - redis
      #- elasticsearch
      - discovery-server
      
      
      
    ports:
      - "8082:8082"

    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/taskflow_project
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      ELASTIC_SEARCH: http://elasticsearch:9200
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: project-service
      OTEL_EXPORTER_OTLP_TIMEOUT: "30000"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"

    networks:
      - taskflow-network
      
      
  task-service:
    image: taskflow/task-service:1.0
    container_name: task-service

    depends_on:
      - postgres
      - otel-collector
      - kafka
      - redis
      - discovery-server
     

    ports:
      - "8083:8083"
      

    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/taskflow_task
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      EUREKA_SERVER: http://discovery-server:8761/eureka/
      JAVA_TOOL_OPTIONS: "-javaagent:/otel/opentelemetry-javaagent.jar"
      OTEL_SERVICE_NAME: task-service
      OTEL_EXPORTER_OTLP_TIMEOUT: "30000"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_INSTRUMENTATION_LOGBACK_MDC_ENABLED: "true"

    networks:
      - taskflow-network
  
  
  
volumes:
  postgres_data:

networks:
  taskflow-network:
   