version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: taskflow-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: taskflow_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - taskflow-network
  
  discovery-server:
    image: taskflow/discovery-server:1.0
    container_name: discovery-server

    ports:
      - "8761:8761"

    networks:
      - taskflow-network

  auth-service:
    image: taskflow/auth-service:1.0
    container_name: auth-service

    depends_on:
      - postgres

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://postgres:5432/taskflow_auth
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      EUREKA_SERVER: http://discovery-server:8761/eureka/

    networks:
      - taskflow-network
  
  api-gateway:
    image: taskflow/api-gateway:1.0
    container_name: api-gateway

    depends_on:
      - discovery-server

    environment:
      SPRING_PROFILES_ACTIVE: docker

      EUREKA_SERVER: http://discovery-server:8761/eureka/

    ports:
      - "8080:8080"

    networks:
      - taskflow-network


volumes:
  postgres_data:

networks:
  taskflow-network: