#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/taskflow_notification
#    username: postgres
#    password: postgres123
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration