spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    distribution:
      percentiles-histogram:
        # This turns on the hidden _bucket metrics for your HTTP endpoints
        http.server.requests: true
    tags:
      application: ${spring.application.name}