spring:
  application:
    name: auth-service

  profiles:
    active: local

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO

jwt:
  secret: 9d8f7a6b5c4d3e2f1a9b8c7d6e5f4a3b9d8f7a6b5c4d3e2f1a9b8c7d6e5f4a3b
  expiration: 3600000
  