spring:
  application:
    name: project-service
  profiles:
    active: local
  
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
  
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true